### PR TITLE
docs:  Add the Contributors file

### PR DESCRIPTION
**Pull request by eduazocar**
### Contribution description

This is a PR to add the Collaborators file, where are all the collaborators who work in this repository.

### CODE REVIEW

**Comment by luisan00** [comment]
Add please as header of the doc, the following:
Here is an inevitably incomplete list in alphabetical order of people who have submitted patches, reported bugs, added translations, helped answer newbie questions.

**Comment by eduazocar** [comment]
> Add please as header of the doc, the following: Here is an inevitably incomplete list in alphabetical order of people who have submitted patches, reported bugs, added translations, helped answer newbie questions.

Do you want to change format to .md or I should to apply that header in simple text?

**Comment by luisan00** [comment]
With plain text is ok but on top the document. I
 mean

**Comment by luisan00** [comment]
Looks good, if it's finished we can moving forward  this PR

**Review by luisan00 — APPROVED** [review]
💯

**Pull request merged**
